"use client";
import { useEffect,useState } from "react";
type Doc={id:string;filename:string;mimeType:string;bytes:number;uploadedAt:string};
type Loan={id:string;name:string;phone:string;principal:number;rate:number;interestMode:string;notes:string;firstDue:string;installment:number};
type Payment={id:string;amount:number;paidAt:string;allocation:string;note:string};
const money=(n:number)=>new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN"}).format(n);
export default function Dossier({loan,related,payments}:{loan:Loan;related:Loan[];payments:Payment[]}){
 const [docs,setDocs]=useState<Doc[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function refresh(){try{const r=await fetch(`/api/loans/${loan.id}/documents`,{cache:"no-store"});const data:any=await r.json();if(!r.ok)throw Error(data.error);setDocs(data)}catch(e){setError(e instanceof Error?e.message:"No se pudieron cargar documentos")}}
 useEffect(()=>{void refresh()},[loan.id]);
 async function upload(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const form=e.currentTarget;try{const r=await fetch(`/api/loans/${loan.id}/documents`,{method:"POST",body:new FormData(form)});const data:any=await r.json();if(!r.ok)throw Error(data.error);form.reset();await refresh()}catch(e){setError(e instanceof Error?e.message:"No se pudo subir") }finally{setBusy(false)}}
 async function remove(id:string){if(!window.confirm("¿Eliminar este documento del expediente?"))return;setBusy(true);try{const r=await fetch(`/api/documents/${id}`,{method:"DELETE"});if(!r.ok)throw Error("No se pudo eliminar");setDocs(xs=>xs.filter(x=>x.id!==id))}catch(e){setError(e instanceof Error?e.message:"Error") }finally{setBusy(false)}}
 return <main className="shell dossier"><header className="top"><div className="brand"><strong>Expediente de {loan.name}</strong></div><a href="/">Volver a la cartera</a></header><section className="heading"><div><h1>{loan.name}</h1><p>{loan.phone||"Sin teléfono"} · {related.length} préstamo(s) registrados</p><p>{loan.notes||"Sin notas adicionales"}</p></div></section><section className="chart-card"><h2>Préstamos de esta persona</h2><ul className="document-list">{related.map(item=><li key={item.id}><span>{item.firstDue} · Capital {money(item.principal)} · Cuota {money(item.installment)}</span><a href={`/expedientes/${item.id}`}>Ver préstamo</a></li>)}</ul></section><section className="chart-card"><h2>Documentos escaneados</h2><p>Desde el teléfono puedes tomar una foto o elegir un PDF. Máximo 10 MB por archivo.</p><form className="document-upload" onSubmit={upload}><label>Archivo o escaneo<input type="file" name="file" accept=".pdf,.png,.jpg,.jpeg,application/pdf,image/png,image/jpeg" required/></label><button className="primary" disabled={busy}>{busy?"Guardando…":"Subir documento"}</button></form><form className="document-upload" onSubmit={upload}><label>Tomar foto con el teléfono<input type="file" name="file" accept="image/*" capture="environment" required/></label><button className="outline" disabled={busy}>Subir foto</button></form>{error&&<p role="alert" className="late">{error}</p>}{docs.length?<ul className="document-list">{docs.map(d=><li key={d.id}><a href={`/api/documents/${d.id}`} target="_blank" rel="noopener noreferrer">{d.filename}</a><span>{(d.bytes/1024/1024).toFixed(1)} MB · {d.uploadedAt.slice(0,10)}</span><button className="outline" disabled={busy} onClick={()=>remove(d.id)}>Eliminar</button></li>)}</ul>:<p>Este expediente aún no tiene documentos.</p>}</section><section className="chart-card"><h2>Movimientos</h2>{payments.length?<ul className="document-list">{payments.map(p=><li key={p.id}>{p.paidAt} · {money(p.amount)} · {p.allocation} · {p.note}</li>)}</ul>:<p>Sin cobros registrados.</p>}</section></main>
}
