"use client";
import { useMemo, useState } from "react";
import { ArrowLeft, BarChart3, BookOpen, Wallet } from "lucide-react";

type Loan={id:string;name:string;principal:number;monthlyCharge:number;rate:number;interestMode:string;createdAt:string;sourceRef:string|null};
type Payment={id:string;loanId:string;amount:number;allocation:string;paidAt:string;note:string};
type Entry={label:string;amount:number;date?:string};
const money=(n:number)=>new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN"}).format(n);
const dateLabel=(date:string)=>new Intl.DateTimeFormat("es-MX",{month:"short",year:"2-digit",timeZone:"UTC"}).format(new Date(date+"T12:00:00Z"));
const sum=(xs:{amount:number}[])=>xs.reduce((total,row)=>total+row.amount,0);
function TAccount({title,debits,credits,note}:{title:string;debits:Entry[];credits:Entry[];note?:string}){const debit=sum(debits),credit=sum(credits);return <article className="taccount"><div className="taccount-title"><h3>{title}</h3>{note&&<small>{note}</small>}</div><div className="taccount-columns"><div><b>DEBE</b>{debits.map((e,i)=><p key={i}><span>{e.label}</span><strong>{money(e.amount)}</strong></p>)}</div><div><b>HABER</b>{credits.map((e,i)=><p key={i}><span>{e.label}</span><strong>{money(e.amount)}</strong></p>)}</div></div><footer><span>Debe {money(debit)} · Haber {money(credit)}</span><strong>Saldo {debit>=credit?"deudor":"acreedor"}: {money(Math.abs(debit-credit))}</strong></footer></article>}
export default function Reports({loans,payments}:{loans:Loan[];payments:Payment[]}){
 const [view,setView]=useState<"graficas"|"mayor"|"balance">("graficas");
 const data=useMemo(()=>{const principal=loans.reduce((a,l)=>a+l.principal,0);const by=(type:string)=>payments.filter(p=>p.allocation===type);const returned=sum(by("principal")),interest=sum(by("interest")),unclassified=sum(payments.filter(p=>p.allocation==="combined"||p.allocation==="unverified")),collected=sum(payments),receivable=Math.max(0,principal-returned);const monthly=Array.from({length:12},(_,i)=>{const d=new Date();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()-(11-i));const key=d.toISOString().slice(0,7);return {key,label:dateLabel(key+"-01"),amount:sum(payments.filter(p=>p.paidAt.startsWith(key)))}});return {principal,returned,interest,unclassified,collected,receivable,monthly}},[loans,payments]);
 const ranked=[...loans].sort((a,b)=>b.principal-a.principal);
 const maxLoan=Math.max(1,...ranked.map(l=>l.principal));const maxMonth=Math.max(1,...data.monthly.map(m=>m.amount));
 const loanEntries=loans.map(l=>({label:l.name,amount:l.principal}));
 const principalEntries=payments.filter(p=>p.allocation==="principal").map(p=>({label:`${p.paidAt} · ${loans.find(l=>l.id===p.loanId)?.name||"Préstamo"}`,amount:p.amount}));
 const collectionEntries=payments.map(p=>({label:`${p.paidAt} · ${loans.find(l=>l.id===p.loanId)?.name||"Préstamo"}`,amount:p.amount}));
 const interestEntries=payments.filter(p=>p.allocation==="interest").map(p=>({label:`${p.paidAt} · ${loans.find(l=>l.id===p.loanId)?.name||"Préstamo"}`,amount:p.amount}));
 const unknownEntries=payments.filter(p=>p.allocation==="combined"||p.allocation==="unverified").map(p=>({label:`${p.paidAt} · ${loans.find(l=>l.id===p.loanId)?.name||"Préstamo"}`,amount:p.amount}));
 const side=data.receivable+data.collected;const counterpart=data.principal+data.interest+data.unclassified;
 return <main className="shell reports"><header className="top"><div className="brand"><div className="brandmark"><BarChart3 size={22}/></div><div><strong>Reportes de cartera</strong><small>Préstamos y movimientos</small></div></div><a className="back" href="/"><ArrowLeft size={16}/> Volver a préstamos</a></header>
 <section className="heading"><div><p className="eyebrow">BALANCE Y MAYOR</p><h1>Situación de la cartera</h1><p>Datos registrados hasta hoy. Los cobros sin desglose siguen pendientes de conciliación.</p></div></section>
 <nav className="report-tabs" aria-label="Vistas del reporte"><button className={view==="graficas"?"active":""} onClick={()=>setView("graficas")}><BarChart3 size={17}/> Gráficas</button><button className={view==="mayor"?"active":""} onClick={()=>setView("mayor")}><BookOpen size={17}/> Esquemas de mayor</button><button className={view==="balance"?"active":""} onClick={()=>setView("balance")}><Wallet size={17}/> Balance general</button></nav>
 <section className="report-kpis"><article><span>Capital prestado</span><strong>{money(data.principal)}</strong></article><article><span>Capital aplicado</span><strong>{money(data.returned)}</strong></article><article><span>Cartera por cobrar identificada</span><strong>{money(data.receivable)}</strong></article><article><span>Cobros por clasificar</span><strong>{money(data.unclassified)}</strong></article></section>
 {view==="graficas"&&<div className="report-stack"><div className="chart-card"><div className="chart-title"><h2>Capital por persona</h2><span>{loans.length} préstamos</span></div><div className="bar-list">{ranked.map(l=><div className="bar-row" key={l.id}><span title={l.name}>{l.name}</span><div className="track"><div style={{width:`${l.principal/maxLoan*100}%`}}/></div><b>{money(l.principal)}</b></div>)}</div></div><div className="chart-card"><div className="chart-title"><h2>Cobros por mes</h2><span>Últimos 12 meses</span></div><div className="month-chart">{data.monthly.map(m=><div className="month-col" key={m.key} title={`${m.label}: ${money(m.amount)}`}><span>{m.amount?money(m.amount):""}</span><div className="month-track"><div style={{height:`${m.amount/maxMonth*100}%`}}/></div><small>{m.label}</small></div>)}</div></div><div className="chart-card"><div className="chart-title"><h2>Destino de los cobros registrados</h2><span>{money(data.collected)} en total</span></div><div className="composition" role="img" aria-label={`Capital ${money(data.returned)}, intereses ${money(data.interest)}, por clasificar ${money(data.unclassified)}`}><div className="principal" style={{width:`${data.collected?data.returned/data.collected*100:0}%`}}/><div className="interest" style={{width:`${data.collected?data.interest/data.collected*100:0}%`}}/><div className="pending" style={{width:`${data.collected?data.unclassified/data.collected*100:0}%`}}/></div><div className="legend"><span><i className="principal"/> Capital {money(data.returned)}</span><span><i className="interest"/> Interés {money(data.interest)}</span><span><i className="pending"/> Por clasificar {money(data.unclassified)}</span></div></div></div>}
 {view==="mayor"&&<section className="ledger-section"><div className="section-intro"><h2>Esquemas de mayor</h2><p>Cada cobro aparece en el Debe de «Cobros reportados» y en el Haber de la cuenta donde se aplica. Cada capital prestado aparece en el Debe de «Préstamos por cobrar» y en una contrapartida pendiente de conciliar.</p></div><div className="taccounts"><TAccount title="Préstamos por cobrar" debits={loanEntries} credits={principalEntries}/><TAccount title="Cobros reportados" debits={collectionEntries} credits={[]} note="Cuenta de control; no equivale al saldo bancario"/><TAccount title="Intereses cobrados" debits={[]} credits={interestEntries}/><TAccount title="Cobros por clasificar" debits={[]} credits={unknownEntries}/><TAccount title="Origen del capital por conciliar" debits={[]} credits={loanEntries} note="Falta determinar efectivo inicial, aportaciones o pasivos"/></div></section>}
 {view==="balance"&&<section className="balance-sheet"><div className="section-intro"><h2>Balance general provisional de cartera</h2><p>Este cuadro cuadra los movimientos registrados. Es un control parcial: el Excel no contiene saldo inicial de caja o bancos, deudas ni aportaciones para emitir un balance general contable definitivo.</p></div><div className="balance-grid"><div className="balance-pane"><h3>Activo de control</h3><div><span>Préstamos por cobrar</span><b>{money(data.receivable)}</b></div><div><span>Cobros reportados*</span><b>{money(data.collected)}</b></div><footer><span>Total</span><b>{money(side)}</b></footer></div><div className="balance-pane"><h3>Contrapartidas y resultado</h3><div><span>Origen del capital por conciliar</span><b>{money(data.principal)}</b></div><div><span>Intereses cobrados identificados</span><b>{money(data.interest)}</b></div><div><span>Cobros por clasificar</span><b>{money(data.unclassified)}</b></div><footer><span>Total</span><b>{money(counterpart)}</b></footer></div></div><p className="balance-foot">* «Cobros reportados» suma entradas anotadas y no afirma cuánto dinero sigue en caja o bancos. La contrapartida del capital tampoco se clasifica como patrimonio o deuda hasta contar con el origen real. Diferencia de control: {money(side-counterpart)}.</p></section>}
 </main>
}
