"use client";
import { scheduleStatus } from "@/lib/loan-schedule";
import { useMemo, useState } from "react";
import { Plus, Wallet, CalendarDays, MessageCircle, Search, History } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { toast, Toaster } from "sonner";

type SourceEntry={id:string;loanId:string|null;sourceCell:string;kind:string;value:string};
type Loan={id:string;borrowerId:string|null;name:string;phone:string;principal:number;interestMode:string;rate:number;installment:number;firstDue:string;frequencyDays:number;dueMode:string;monthlyCharge:number;notes:string;consent:number;reminderDays:number;messageTemplate:string;sourceRef:string|null;scheduleKnown:number;createdAt:string};
type Payment={id:string;loanId:string;amount:number;paidAt:string;allocation:string;note:string;sourceRef:string|null};
const money=(v:number)=>new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN"}).format(v);
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Mexico_City",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
function nextSemiDue(){const [y,m,day]=today().split("-").map(Number);const d=day<=15?new Date(Date.UTC(y,m-1,15)):new Date(Date.UTC(y,m,0));return d.toISOString().slice(0,10)}
export default function Dashboard({initialLoans,initialPayments,initialSourceEntries}:{initialLoans:Loan[];initialPayments:Payment[];initialSourceEntries:SourceEntry[]}){
 const [items,setItems]=useState(initialLoans),[payments,setPayments]=useState(initialPayments),[open,setOpen]=useState(false),[pay,setPay]=useState<Loan|null>(null),[history,setHistory]=useState<Loan|null>(null),[editing,setEditing]=useState<Loan|null>(null),[messageLoan,setMessageLoan]=useState<Loan|null>(null),[draft,setDraft]=useState(""),[search,setSearch]=useState(""),[busy,setBusy]=useState(false);
 const rows=useMemo(()=>items.map(l=>{const p=payments.filter(x=>x.loanId===l.id),paid=p.reduce((a,x)=>a+x.amount,0),capitalPaid=p.filter(x=>x.allocation==="principal").reduce((a,x)=>a+x.amount,0),eligible=p.filter(x=>x.allocation==="interest"||x.allocation==="combined").reduce((a,x)=>a+x.amount,0);return {...l,paid,capitalPaid,monthlyReference:l.interestMode==="none"?0:l.monthlyCharge||(l.interestMode==="balance"?Math.max(0,l.principal-capitalPaid):l.principal)*l.rate/100,...scheduleStatus(l,l.interestMode==="none"?capitalPaid:eligible,today())}}),[items,payments]);
 const shown=rows.filter(l=>l.name.toLocaleLowerCase("es").includes(search.toLocaleLowerCase("es")));
 async function submitLoan(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const payload={borrowerId:String(f.get("borrowerId")||"")||undefined,name:String(f.get("name")),phone:String(f.get("phone")),principal:Number(f.get("principal")),interestMode:String(f.get("interestMode")),rate:Number(f.get("rate")),installment:Number(f.get("installment")),firstDue:String(f.get("firstDue")),frequencyDays:Number(f.get("frequencyDays")),dueMode:String(f.get("dueMode")),monthlyCharge:Number(f.get("monthlyCharge")),notes:String(f.get("notes")),consent:false,reminderDays:0};try{const r=await fetch("/api/loans",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data:any=await r.json();if(!r.ok)throw Error(data.error);setItems(x=>[data,...x]);setOpen(false);toast.success("Préstamo guardado")}catch(e){toast.error(e instanceof Error?e.message:"Error al guardar")}finally{setBusy(false)}}
 async function submitPayment(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!pay)return;setBusy(true);const f=new FormData(e.currentTarget);try{const r=await fetch("/api/payments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({loanId:pay.id,amount:Number(f.get("amount")),paidAt:String(f.get("paidAt")),allocation:String(f.get("allocation")),note:String(f.get("note"))})});const data:any=await r.json();if(!r.ok)throw Error(data.error);setPayments(x=>[data,...x]);setPay(null);toast.success("Movimiento registrado")}catch(e){toast.error(e instanceof Error?e.message:"Error al guardar")}finally{setBusy(false)}}
 const defaultMessage=(l:Loan)=>l.scheduleKnown&&l.installment>0?`Hola, {nombre}. Te recordamos que tu pago de {cuota} vence el {fecha}. Si ya realizaste tu pago, por favor ignora este mensaje. Gracias.`:`Hola, {nombre}. Te escribimos para revisar el pago de tu préstamo. Si ya realizaste un abono, por favor avísanos. Gracias.`;
 function openMessage(l:Loan){setMessageLoan(l);setDraft(l.messageTemplate||defaultMessage(l))}
 function messageText(l:Loan){const row=rows.find(x=>x.id===l.id);return draft.replaceAll("{nombre}",l.name).replaceAll("{cuota}",money(l.installment)).replaceAll("{fecha}",row?.next||"fecha por confirmar")}
 function whatsappUrl(l:Loan){let digits=l.phone.replace(/\D/g,"");if(digits.length===10)digits="52"+digits;return digits.length>=11&&digits.length<=15?`https://wa.me/${digits}?text=${encodeURIComponent(messageText(l))}`:""}
 async function saveMessage(){if(!messageLoan||!draft.trim())return;setBusy(true);try{const r=await fetch(`/api/loans/${messageLoan.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({messageTemplate:draft.trim()})});const data:any=await r.json();if(!r.ok)throw Error(data.error);setItems(x=>x.map(l=>l.id===messageLoan.id?{...l,messageTemplate:data.messageTemplate}:l));setMessageLoan({...messageLoan,messageTemplate:data.messageTemplate});toast.success("Mensaje guardado")}catch(e){toast.error(e instanceof Error?e.message:"No se pudo guardar")}finally{setBusy(false)}}
 async function saveTerms(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;setBusy(true);const f=new FormData(e.currentTarget);const payload={name:String(f.get("name")),phone:String(f.get("phone")),principal:Number(f.get("principal")),interestMode:String(f.get("interestMode")),rate:Number(f.get("rate")),monthlyCharge:Number(f.get("monthlyCharge")),installment:Number(f.get("installment")),firstDue:String(f.get("firstDue")),frequencyDays:Number(f.get("frequencyDays")),dueMode:String(f.get("dueMode")),notes:String(f.get("notes"))};try{const r=await fetch(`/api/loans/${editing.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data:any=await r.json();if(!r.ok)throw Error(data.error);setItems(x=>x.map(l=>l.id===editing.id?{...l,...data}:editing.borrowerId&&l.borrowerId===editing.borrowerId?{...l,name:data.name,phone:data.phone}:l));setEditing(null);toast.success("Condiciones actualizadas")}catch(e){toast.error(e instanceof Error?e.message:"No se pudo guardar")}finally{setBusy(false)}}
 async function classifyPayment(p:Payment,allocation:string){setBusy(true);try{const r=await fetch(`/api/payments/${p.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({allocation})});const data:any=await r.json();if(!r.ok)throw Error(data.error);setPayments(x=>x.map(row=>row.id===p.id?{...row,allocation:data.allocation}:row));toast.success("Cobro clasificado")}catch(e){toast.error(e instanceof Error?e.message:"No se pudo clasificar")}finally{setBusy(false)}}
 const capital=rows.reduce((a,l)=>a+l.principal,0),collected=payments.reduce((a,p)=>a+p.amount,0),allocatedCapital=rows.reduce((a,l)=>a+l.capitalPaid,0),unverified=payments.filter(p=>p.allocation==="unverified").reduce((a,p)=>a+p.amount,0);
 return <main className="shell"><Toaster richColors position="top-right"/><header className="top"><div className="brand"><div className="brandmark"><Wallet size={22}/></div><div><strong>Cartera</strong><small>Control de préstamos</small></div></div><div className="top-actions"><a className="report-link" href="/reportes">Gráficas y balance</a><button className="outline" onClick={async()=>{await fetch("/api/auth/logout",{method:"POST"});location.assign("/ingresar")}}>Salir</button></div></header>
 <section className="heading"><div><p className="eyebrow">PANEL DE CONTROL</p><h1>Préstamos y pagos</h1><p>Capital, cargos pactados, cobros y vencimientos en un solo lugar.</p></div><button className="primary" onClick={()=>setOpen(true)}><Plus size={18}/> Nuevo préstamo</button></section>
 <section className="balance"><div><p className="eyebrow">BALANCE DE CARTERA</p><h2>{money(Math.max(0,capital-allocatedCapital))}</h2><p>Capital sin abonos aplicados · de {money(capital)} originalmente prestados</p></div><div className="balance-side"><span>Cobros documentados <strong>{money(collected)}</strong></span><span>Sin clasificación <strong>{money(unverified)}</strong></span></div></section>
 <section className="metrics"><article><span>Préstamos registrados</span><strong>{items.length}</strong></article><article><span>Cargo mensual de referencia</span><strong>{money(rows.reduce((a,l)=>a+l.monthlyReference,0))}</strong></article><article><span>Abonos aplicados a capital</span><strong>{money(allocatedCapital)}</strong></article><article><span>Calendarios por revisar</span><strong>{rows.filter(r=>!r.scheduleKnown).length}</strong></article></section>
 <p className="balancehint">El capital mostrado no descuenta los cobros sin desglose. Clasifícalos en Movimientos para calcular el capital pendiente identificado.</p>
 <section className="list"><div className="listhead"><div><h2>Personas y préstamos</h2><span>{shown.length} registros</span></div><label className="search"><Search size={17}/><input placeholder="Buscar por nombre" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>
 {shown.length?shown.map(l=><article className="loan" key={l.id}><div className="avatar">{l.name.slice(0,1).toUpperCase()}</div><div className="loanmain"><strong>{l.name}</strong><span>{l.phone||"Sin teléfono"} · {l.interestMode==="none"?"Sin interés":l.interestMode==="fixed"?"Interés fijo":l.interestMode==="balance"?"Sobre saldo":"Acuerdo particular"}{l.rate>0?` · ${l.rate}% pactado`:""}</span><small>Capital {money(l.principal)} · Cobrado {money(l.paid)} · Capital por conciliar {money(Math.max(0,l.principal-l.capitalPaid))}{l.monthlyReference>0?` · Referencia mensual ${money(l.monthlyReference)}`:""}</small></div><div className="loandue"><b>{l.scheduleKnown?money(l.installment):"Cuota por confirmar"}</b><span><CalendarDays size={14}/> {l.settled?"Sin próximo cobro":l.next||"Fecha por confirmar"}</span><em className={l.late?"late":"current"}>{l.settled?"Capital liquidado":!l.scheduleKnown?"Revisar condiciones":l.late?`Pendiente ${money(l.unpaid)}`:"Al corriente según cuotas"}</em></div><div className="actions"><a className="outline" href={`/expedientes/${l.id}`}>Expediente</a><button className="outline" onClick={()=>setEditing(l)}>Editar</button><button className="outline" onClick={()=>setPay(l)}>Registrar cobro</button><button className="outline" onClick={()=>setHistory(l)}><History size={16}/> Movimientos</button><button className="outline whatsapp" onClick={()=>openMessage(l)}><MessageCircle size={16}/> Mensaje</button></div></article>):<div className="empty">{items.length?"No hay coincidencias.":"Aún no tienes préstamos. Agrega el primero para empezar."}</div>}</section>

 {initialSourceEntries.some(e=>!e.loanId&&e.kind!=="encabezado")&&<details className="raw unlinked"><summary>Ver cifras del Excel sin persona asignada</summary><div>{initialSourceEntries.filter(e=>!e.loanId&&e.kind!=="encabezado").map(e=><p key={e.id}><b>{e.sourceCell}</b> {e.value}</p>)}</div><p className="hint">Estas cifras no se suman al balance porque el archivo no indica a quién corresponden.</p></details>}
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="modal"><DialogHeader><DialogTitle>Nuevo préstamo</DialogTitle></DialogHeader><form onSubmit={submitLoan} className="form"><div className="grid2"><label>Persona ya registrada<select name="borrowerId" defaultValue="" onChange={e=>{const person=items.find(x=>x.borrowerId===e.target.value);const form=e.currentTarget.form;if(person&&form){(form.elements.namedItem("name") as HTMLInputElement).value=person.name;(form.elements.namedItem("phone") as HTMLInputElement).value=person.phone}}}><option value="">Nueva persona</option>{[...new Map(items.filter(x=>x.borrowerId).map(x=>[x.borrowerId,x])).values()].map(x=><option key={x.borrowerId} value={x.borrowerId||""}>{x.name} · {x.phone||"Sin teléfono"}</option>)}</select></label><label>Nombre de la persona<input name="name" required minLength={2} placeholder="Nombre completo"/></label><label>WhatsApp<input name="phone" type="tel" placeholder="443…"/></label><label>Capital entregado<input name="principal" type="number" min="0.01" step="0.01" required/></label><label>Tipo de acuerdo<select name="interestMode" defaultValue="fixed"><option value="fixed">Interés fijo sobre capital inicial</option><option value="balance">Interés sobre capital pendiente</option><option value="none">Sin interés</option><option value="manual">Importe pactado manualmente</option></select></label><label>Porcentaje mensual pactado (%)<input name="rate" type="number" min="0" max="1000" step="0.01" defaultValue="0" required/></label><label>Cargo mensual pactado, si difiere del porcentaje<input name="monthlyCharge" type="number" min="0" step="0.01" defaultValue="0" required/></label><label>Cuota que debe pagar en cada fecha<input name="installment" type="number" min="0.01" step="0.01" required/></label><label>Primera fecha de cobro<input name="firstDue" type="date" defaultValue={nextSemiDue()} required/></label><label>Calendario<select name="dueMode" defaultValue="semi_monthly"><option value="semi_monthly">Días 15 y último de cada mes</option><option value="interval">Cada cierto número de días</option></select></label><label>Días entre cobros (si eliges intervalo)<input name="frequencyDays" type="number" min="1" max="365" defaultValue="15" required/></label><label className="wide">Condiciones particulares<input name="notes" placeholder="Ej. paga solo intereses; capital al final"/></label></div><p className="hint">El cargo mensual es una referencia del acuerdo; si escribes un importe, tiene prioridad sobre porcentaje × capital. Registra cada cobro como interés, capital o sin desglose. Los cobros sin desglose no reducen el capital mostrado.</p><button disabled={busy} className="primary full">{busy?"Guardando…":"Guardar préstamo"}</button></form></DialogContent></Dialog>
 <Dialog open={!!pay} onOpenChange={v=>{if(!v)setPay(null)}}><DialogContent className="modal small"><DialogHeader><DialogTitle>Registrar cobro</DialogTitle></DialogHeader><p className="muted">{pay?.name}</p><form onSubmit={submitPayment} className="form"><label>Monto recibido<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>Fecha del cobro<input name="paidAt" type="date" defaultValue={today()} required/></label><label>Aplicación del dinero<select name="allocation" defaultValue={pay?.interestMode==="none"?"principal":"interest"}><option value="interest">Interés o cuota periódica</option><option value="principal">Abono a capital</option><option value="combined">Sin desglose / mixto</option></select></label><label>Nota<input name="note" placeholder="Efectivo, transferencia, acuerdo…"/></label><button className="primary full" disabled={busy}>{busy?"Guardando…":"Guardar cobro"}</button></form></DialogContent></Dialog>
 <Dialog open={!!history} onOpenChange={v=>{if(!v)setHistory(null)}}><DialogContent className="modal"><DialogHeader><DialogTitle>Movimientos de {history?.name}</DialogTitle></DialogHeader><p className="muted">Capital original: {money(history?.principal||0)}</p><div className="ledger">{payments.filter(p=>p.loanId===history?.id).sort((a,b)=>b.paidAt.localeCompare(a.paidAt)).map(p=><div className="ledgerrow" key={p.id}><div><strong>{p.paidAt}</strong><small>{p.note||"Cobro registrado"}</small><label className="classify">Aplicación<select aria-label={`Clasificar cobro de ${money(p.amount)} del ${p.paidAt}`} value={p.allocation} disabled={busy} onChange={e=>classifyPayment(p,e.target.value)}><option value="unverified">Por clasificar</option><option value="interest">Interés / cuota</option><option value="principal">Capital</option><option value="combined">Mixto sin desglose</option></select></label></div><b>{money(p.amount)}</b></div>)}{!payments.some(p=>p.loanId===history?.id)&&<p className="muted">Aún no hay cobros confirmados.</p>}</div>{history?.notes&&<p className="hint">Acuerdo: {history.notes}</p>}{history?.sourceRef&&<details className="raw"><summary>Ver celdas originales del Excel ({initialSourceEntries.filter(e=>e.loanId===history.id).length})</summary><div>{initialSourceEntries.filter(e=>e.loanId===history.id&&e.kind!=="encabezado").map(e=><p key={e.id}><b>{e.sourceCell}</b> {e.value}</p>)}</div></details>}</DialogContent></Dialog>
 <Dialog open={!!editing} onOpenChange={v=>{if(!v)setEditing(null)}}><DialogContent className="modal"><DialogHeader><DialogTitle>Confirmar condiciones de {editing?.name}</DialogTitle></DialogHeader>{editing&&<form onSubmit={saveTerms} className="form" key={editing.id}><p className="hint">Revisa la cuota y la primera fecha. El Excel no permite asegurar cómo se aplicó cada cobro; conserva el historial y clasifícalo por separado.</p><div className="grid2"><label>Nombre<input name="name" defaultValue={editing.name} required/></label><label>WhatsApp<input name="phone" defaultValue={editing.phone}/></label><label>Capital entregado<input name="principal" type="number" min="0.01" step="0.01" defaultValue={editing.principal} required/></label><label>Tipo de acuerdo<select name="interestMode" defaultValue={editing.interestMode}><option value="fixed">Interés fijo</option><option value="balance">Sobre capital pendiente</option><option value="none">Sin interés</option><option value="manual">Acuerdo manual</option></select></label><label>Porcentaje mensual (%)<input name="rate" type="number" min="0" max="1000" step="0.01" defaultValue={editing.rate} required/></label><label>Cargo mensual pactado<input name="monthlyCharge" type="number" min="0" step="0.01" defaultValue={editing.monthlyCharge} required/></label><label>Cuota por fecha<input name="installment" type="number" min="0.01" step="0.01" defaultValue={editing.installment||""} required/></label><label>Primer vencimiento<input name="firstDue" type="date" defaultValue={editing.firstDue} required/></label><label>Calendario<select name="dueMode" defaultValue={editing.dueMode}><option value="semi_monthly">Días 15 y último del mes</option><option value="interval">Intervalo en días</option></select></label><label>Días entre cobros (si aplica)<input name="frequencyDays" type="number" min="1" max="365" defaultValue={editing.frequencyDays} required/></label><label className="wide">Notas<input name="notes" defaultValue={editing.notes}/></label></div><button className="primary full" disabled={busy}>{busy?"Guardando…":"Confirmar y guardar condiciones"}</button></form>}</DialogContent></Dialog>
 <Dialog open={!!messageLoan} onOpenChange={v=>{if(!v)setMessageLoan(null)}}><DialogContent className="modal small"><DialogHeader><DialogTitle>Mensaje para {messageLoan?.name}</DialogTitle></DialogHeader><div className="form"><p className="hint">Usa {'{nombre}'}, {'{cuota}'} y {'{fecha}'}. Se sustituyen al abrir WhatsApp.</p><label>Texto del recordatorio<textarea rows={7} maxLength={1200} value={draft} onChange={e=>setDraft(e.target.value)}/></label><button className="outline" onClick={()=>messageLoan&&setDraft(defaultMessage(messageLoan))}>Generar mensaje predeterminado</button><div className="preview"><strong>Vista previa</strong><p>{messageLoan?messageText(messageLoan):""}</p></div><button className="outline" onClick={saveMessage} disabled={busy||!draft.trim()}>Guardar para este préstamo</button>{messageLoan&&whatsappUrl(messageLoan)?<a className="primary full" href={whatsappUrl(messageLoan)} target="_blank" rel="noopener noreferrer">Abrir WhatsApp para enviarlo</a>:<p className="hint">Agrega un teléfono válido al préstamo para abrir WhatsApp.</p>}<p className="hint">WhatsApp no lo envía por sí solo. Revisa el texto y toca Enviar.</p></div></DialogContent></Dialog></main>
}
